##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # cafe B-D: libctk-3-dev

before_scripts:
#  - ./html-cppcheck
  - ./debrepo-install

build_scripts:
#  - ./before-build
#  - ./make-scanbuild
#  - ./after-build
  - ./build-debs https://github.com/cafe-desktop/debian-packages devel libkanberra

after_scripts:
  - ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/categories/applications-multimedia.png
