##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - aptitude
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - git
    - gnome-pkg-tools
    - gtk-doc-tools
    - libltdl-dev
    - libasound2-dev
    - libvorbis-dev
    - libtdb-dev
    - libpulse-dev
    - libgstreamer1.0-dev

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 libctk-3-doc'

build_scripts:
  - ./before-build
  - ./make-scanbuild
  - ./after-build

after_scripts:
  - ./gen-index -l 20
